name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a0c4f7f57d # v4.1.1

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - uses: actions/setup-node@60edb5dd5e06b7d1d7753680f897a6b1e9d60ebf # v4.0.2
        with:
          node-version: 23
          cache: pnpm

      - run: pnpm install
      - run: pnpm run build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2e72c6200a576b3e71e1debc99a9e99dbba2b # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            main.js
            styles.css
            manifest.json
